schema_version = "1.0.0"

id = "polyfem"
version = "1.0.13"
name = "PolyFem"
tagline = "PolyFEM simulation plugin for Blender"
maintainer = "Antoine Boucher <antoine@antoineboucher.info>"
type = "add-on"

blender_version_min = "4.2.0"

license = [
  "MIT"
]

website = "https://github.com/ETSTribology/PolyFEMBlenderPlugin"
tags = ["Object", "Physics", "Import-Export"]
platforms = ["windows-x64"]

[permissions]
files = "Required for reading and writing files during export"
network = "Required for accessing online resources or services"
