name: Build and Deploy Add-on

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_stage:
        description: 'Release stage (alpha, beta, rc)'
        required: true
        default: 'alpha'

permissions:
  contents: write

jobs:
  Generate_Matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Tests Matrix
        id: set-matrix
        run: |
          python .github/make-tests-matrix.py >> $GITHUB_OUTPUT

  Build_Addon_And_Deploy:
    needs: Generate_Matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.Generate_Matrix.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Blender Binary
        uses: actions/cache@v3
        with:
          path: /home/runner/blender
          key: blender-${{ matrix.version }}-${{ matrix.sha }}

      - name: Download Blender
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          curl -L ${{ matrix.download_url }} -o blender.tar.xz
          mkdir -p /home/runner/blender
          tar -xf blender.tar.xz --strip-components=1 -C /home/runner/blender

      - name: Add Blender to PATH
        run: echo "/home/runner/blender" >> $GITHUB_PATH

      - name: Build Addon and Place in Docs
        run: |
          mkdir -p docs
          blender --background --python-expr "import bpy; bpy.ops.preferences.extension_build(directory='polyfem/', filepath='docs/polyfem-v${{ matrix.version }}.zip')"

      - name: Generate Static Repository with HTML
        run: |
          blender --background --command extension server-generate --repo-dir=docs --html

      - name: Upload Blender Add-on ZIP
        uses: actions/upload-artifact@v3
        with:
          name: polyfem-${{ matrix.version }}
          path: docs/polyfem-v${{ matrix.version }}.zip

      - name: Touch .nojekyll
        run: |
          cd site
          touch .nojekyll
          cd ..

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: site
          clean: true
