name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_stage:
        description: 'Release stage (alpha, beta, rc)'
        required: true
        default: 'alpha'

permissions:
  contents: write

jobs:
  Build_Addon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Blender
        run: |
          sudo apt-get update
          sudo apt-get install blender

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r polyfem/requirements.txt

      - name: Extract version from blender_manifest.toml
        id: get_version
        run: |
          version=$(sed -n 's/^version = "\(.*\)"/\1/p' polyfem/blender_manifest.toml)
          echo "VERSION=$version" >> $GITHUB_ENV

      - name: Build Addon with Blender
        run: |
          blender --background --python-expr "import bpy; bpy.ops.preferences.extension_build(directory='polyfem/', filepath='docs/physics_export-v${{ env.VERSION }}.zip')"

      - name: Generate Static Repository JSON
        run: |
          blender --background --command extension server-generate --repo-dir=docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
