name: Build and Test

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_stage:
        description: 'Release stage (alpha, beta, rc)'
        required: true
        default: 'alpha'

permissions:
  contents: write

jobs:
  Generate_Matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Generate Tests Matrix
        id: set-matrix
        run: |
          python .github/make-tests-matrix.py >> $GITHUB_OUTPUT

  Test_Addon:
    needs: Generate_Matrix
    runs-on: ubuntu-latest

    strategy:
      matrix: ${{ fromJSON(needs.Generate_Matrix.outputs.matrix) }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Blender
        run: |
          curl -L ${{ matrix.download_url }} -o blender.tar.xz
          tar -xf blender.tar.xz --strip-components=1 -C /home/runner/blender

      - name: Add Blender to PATH
        run: echo "/home/runner/blender" >> $GITHUB_PATH

      - name: Run Addon Tests
        run: |
          blender --background --python-expr "import bpy; bpy.ops.preferences.extension_build(directory='polyfem/', filepath='docs/physics_export-v${{ matrix.version }}.zip')"
      
      - name: Upload Blender Add-on ZIP
        uses: actions/upload-artifact@v3
        with:
          name: PolyFemBlenderPlugin-${{ matrix.version }}
          path: docs/physics_export-v${{ matrix.version }}.zip
